---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
    deployment:
      hosts:
        local-1:
          ansible_host: 10.79.0.11
        local-2:
          ansible_host: 10.79.0.12
        local-3:
          ansible_host: 10.79.0.13
    wireguard_nodes:
      children:
        deployment: {}
