version: "3"

set: [errexit, nounset, pipefail]

includes:
  project:
    taskfile: ./taskfiles/project.yml
    flatten: true
  vault:
    taskfile: ./taskfiles/vault.yml
    flatten: true
  lima:
    taskfile: ./taskfiles/lima.yml
    flatten: true
  wireguard:
    taskfile: ./taskfiles/wireguard.yml
    flatten: true
  cluster:
    taskfile: ./taskfiles/cluster.yml
    flatten: true

tasks:
  default:
    desc: List available tasks
    silent: true
    cmds:
      - task --list

