---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
    deployment:
      hosts:
        static-1:
          prod_wireguard_endpoint: "REPLACE_WITH_STATIC_1_PUBLIC_IPV4"
          prod_ssh_host_ed25519_sha256: "SHA256:REPLACE_WITH_COMPLETE_FINGERPRINT_STATIC_1"
          prod_wireguard_address: 10.217.80.11
        roaming-1:
          wireguard_roaming: true
          node_lima_guest: true
          node_host_architecture: aarch64
          prod_ssh_host_ed25519_sha256: "SHA256:XYxOtnaOjEzcnKMoGaH+97xdFufpT2Tt2z1H+PJDYWs"
          prod_wireguard_address: 10.217.80.21
    wireguard_nodes:
      children:
        deployment: {}
