---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
    deployment:
      hosts:
        static-1:
          wireguard_endpoint: "159.203.27.69"
          ssh_host_ed25519_sha256: "SHA256:pRR2cezc6UOTGq+vTrVwPFCFKlHRKuuV/OL/9/c3e+M"
          wireguard_address: 10.217.80.11
        roaming-1:
          wireguard_roaming: true
          node_lima_guest: true
          node_host_architecture: aarch64
          ssh_host_ed25519_sha256: "SHA256:qo5U1YG4cwNGv0zjqBZZK/7wP6TlYMGSw2LeLuZL8vM"
          wireguard_address: 10.217.80.21
    wireguard_nodes:
      children:
        deployment: {}
