---
all:
  vars:
    project: example
    hostname: sc.example.com

nodes:
  hosts:
    static-1:
      public_ip: "REPLACE_WITH_STATIC_1_PUBLIC_IPV4"
      ssh_ed25519_sha256: "SHA256:REPLACE_WITH_COMPLETE_FINGERPRINT_STATIC_1"
      private_address: 10.217.80.11
