---
all:
  vars:
    project: example
    hostname: sc.example.tanzimsaqib.com

nodes:
  hosts:
    static-1:
      public_ip: "159.203.27.69"
      ssh_ed25519_sha256: "SHA256:pRR2cezc6UOTGq+vTrVwPFCFKlHRKuuV/OL/9/c3e+M"
      private_address: 10.217.81.11
    roaming-1:
      roaming: true
      node_lima_guest: true
      node_host_architecture: aarch64
      ssh_ed25519_sha256: "SHA256:u6H5kCfw8bsbX2gL5FRD8df2uGAAjqzomEBfI5++oxs"
      private_address: 10.217.81.21
