#!/usr/bin/env python3
"""SHA-pinned rathole fetch, inventory helpers, and roaming client bootstrap."""

from __future__ import annotations

import argparse
import hashlib
import ipaddress
import os
from pathlib import Path
import secrets
import sys
import tempfile
import urllib.error
import urllib.request
import zipfile

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import inventory_hosts  # noqa: E402
import vault as provider_vault  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
RATHOLE_VERSION = "0.5.0"
RATHOLE_ARCHIVE_NAME = "rathole-x86_64-unknown-linux-gnu.zip"
RATHOLE_ARCHIVE_URL = (
  f"https://github.com/rapiz1/rathole/releases/download/v{RATHOLE_VERSION}/"
  f"{RATHOLE_ARCHIVE_NAME}"
)
RATHOLE_ARCHIVE_SHA256 = (
  "3e7d0d0f365120cd3cd351d147d1a12ee960c8068b464d4dd533a3821873b80e"
)
VENDOR_DIR = ROOT / ".vendor" / "rathole"
VENDOR_ARCHIVE = VENDOR_DIR / RATHOLE_ARCHIVE_NAME
VENDOR_BINARY = VENDOR_DIR / "rathole"
CONTROL_PORT = 2333
SSH_PORT_BASE = 61000


class RatholeError(RuntimeError):
  pass


def is_roaming(values: dict) -> bool:
  return values.get("roaming") is True


def is_lima_guest(values: dict) -> bool:
  return values.get("node_lima_guest") is True


def is_non_lima_roaming(values: dict) -> bool:
  return is_roaming(values) and not is_lima_guest(values)


def rathole_ssh_port(private_address: str) -> int:
  address = ipaddress.ip_address(private_address)
  if address.version != 4:
    raise RatholeError(f"private_address must be IPv4: {private_address}")
  last = int(str(address).rsplit(".", 1)[1])
  return SSH_PORT_BASE + last


def node_hosts(provider: str) -> dict[str, dict]:
  try:
    return inventory_hosts.node_hosts(inventory_hosts.load_document(provider))
  except inventory_hosts.InventoryError as error:
    raise RatholeError(str(error)) from error


def static_hub_name(hosts: dict[str, dict]) -> str:
  statics = sorted(
    name for name, values in hosts.items() if not is_roaming(values)
  )
  if not statics:
    raise RatholeError("Non-Lima roaming needs at least one static public hub")
  return statics[0]


def non_lima_roaming_names(hosts: dict[str, dict]) -> list[str]:
  return sorted(
    name for name, values in hosts.items() if is_non_lima_roaming(values)
  )


def sha256_file(path: Path) -> str:
  digest = hashlib.sha256()
  with path.open("rb") as handle:
    while True:
      chunk = handle.read(1024 * 1024)
      if not chunk:
        break
      digest.update(chunk)
  return digest.hexdigest()


def fetch_pinned_binary() -> Path:
  VENDOR_DIR.mkdir(parents=True, exist_ok=True)
  if VENDOR_BINARY.is_file() and VENDOR_ARCHIVE.is_file():
    if sha256_file(VENDOR_ARCHIVE) == RATHOLE_ARCHIVE_SHA256:
      print(f"rathole already present: {VENDOR_BINARY}")
      return VENDOR_BINARY
  print(f"Fetching pinned rathole {RATHOLE_VERSION} ({RATHOLE_ARCHIVE_NAME})")
  try:
    urllib.request.urlretrieve(RATHOLE_ARCHIVE_URL, VENDOR_ARCHIVE)
  except urllib.error.URLError as error:
    raise RatholeError(f"Failed to download {RATHOLE_ARCHIVE_URL}: {error}") from error
  observed = sha256_file(VENDOR_ARCHIVE)
  if observed != RATHOLE_ARCHIVE_SHA256:
    VENDOR_ARCHIVE.unlink(missing_ok=True)
    raise RatholeError(
      f"rathole archive sha256 mismatch: expected {RATHOLE_ARCHIVE_SHA256}, "
      f"got {observed}"
    )
  with zipfile.ZipFile(VENDOR_ARCHIVE) as archive:
    names = archive.namelist()
    if names != ["rathole"]:
      raise RatholeError(f"Unexpected rathole archive members: {names}")
    with tempfile.NamedTemporaryFile(
      dir=VENDOR_DIR, prefix=".rathole.", delete=False
    ) as temporary:
      temporary.write(archive.read("rathole"))
      temporary.flush()
      os.fsync(temporary.fileno())
      temporary_path = Path(temporary.name)
  temporary_path.chmod(0o755)
  os.replace(temporary_path, VENDOR_BINARY)
  print(f"rathole installed: {VENDOR_BINARY}")
  return VENDOR_BINARY


def render_client_install_script(
  *,
  node: str,
  hub_endpoint: str,
  listen_port: int,
  token: str,
  noise_public_key: str,
) -> str:
  return f"""#!/usr/bin/env bash
set -Eeuo pipefail
# Generated by scripts/rathole.py render-client. Run once on {node} (console or LAN SSH).
if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root (sudo bash $0)." >&2
  exit 2
fi
archive_url={RATHOLE_ARCHIVE_URL!r}
expected_sha256={RATHOLE_ARCHIVE_SHA256!r}
tmp="$(mktemp -d)"
trap 'rm -rf "${{tmp}}"' EXIT
curl -fsSL -o "${{tmp}}/rathole.zip" "${{archive_url}}"
observed="$(sha256sum "${{tmp}}/rathole.zip" | awk '{{ print $1 }}')"
if [[ "${{observed}}" != "${{expected_sha256}}" ]]; then
  echo "rathole archive sha256 mismatch: ${{observed}}" >&2
  exit 1
fi
python3 - "${{tmp}}/rathole.zip" /usr/local/bin/rathole <<'PY'
import sys
import zipfile
from pathlib import Path
archive, dest = Path(sys.argv[1]), Path(sys.argv[2])
with zipfile.ZipFile(archive) as zf:
  dest.write_bytes(zf.read("rathole"))
dest.chmod(0o755)
PY
install -d -m 0700 /etc/rathole
cat > /etc/rathole/client.toml <<'EOF'
[client]
remote_addr = "{hub_endpoint}:{CONTROL_PORT}"
heartbeat_timeout = 40
retry_interval = 1

[client.transport]
type = "noise"

[client.transport.noise]
remote_public_key = "{noise_public_key}"

[client.services.{node}]
type = "tcp"
token = "{token}"
local_addr = "127.0.0.1:22"
EOF
chmod 0600 /etc/rathole/client.toml
cat > /etc/systemd/system/rathole-client.service <<'EOF'
[Unit]
Description=rathole client (Supercompute roaming SSH bootstrap)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
Restart=always
RestartSec=2s
ExecStart=/usr/local/bin/rathole --client /etc/rathole/client.toml

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now rathole-client.service
systemctl --no-pager --full status rathole-client.service
echo "Rathole client started for {node} (hub {hub_endpoint}, local SSH via 127.0.0.1:{listen_port} on the hub)."
"""


def render_client_uninstall_script(*, node: str) -> str:
  return f"""#!/usr/bin/env bash
set -Eeuo pipefail
# Generated by scripts/rathole.py render-client. Run on {node} (console or LAN SSH).
if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root (sudo bash $0)." >&2
  exit 2
fi
systemctl disable --now rathole-client.service 2>/dev/null || true
rm -f /etc/systemd/system/rathole-client.service
systemctl daemon-reload
rm -f /etc/rathole/client.toml
rmdir /etc/rathole 2>/dev/null || true
rm -f /usr/local/bin/rathole
echo "Rathole client removed from {node}."
"""


def render_client(provider: str, node: str) -> Path:
  hosts = node_hosts(provider)
  if node not in hosts:
    raise RatholeError(f"{node} is not in inventories/{provider}/hosts.yml")
  values = hosts[node]
  if not is_non_lima_roaming(values):
    raise RatholeError(
      f"{node} must be roaming: true without node_lima_guest "
      "(Lima guests do not use rathole)"
    )
  private_address = values.get("private_address")
  if not isinstance(private_address, str) or not private_address:
    raise RatholeError(f"{node} must set private_address")
  listen_port = rathole_ssh_port(private_address)
  hub = static_hub_name(hosts)
  hub_ip = hosts[hub].get("public_ip")
  if not isinstance(hub_ip, str) or not hub_ip or hub_ip.startswith("REPLACE_WITH_"):
    raise RatholeError(f"{hub} must set a real public_ip before rendering the client")

  password_file = provider_vault.password_path(provider)
  encrypted_vault = provider_vault.vault_path(provider)
  provider_vault.read_password(password_file)
  document = yaml.safe_load(
    provider_vault.decrypt(encrypted_vault, provider, password_file)
  )
  if not isinstance(document, dict):
    raise RatholeError("Vault root must be a YAML mapping")
  public_key = document.get("vault_rathole_noise_public_key")
  tokens = document.get("vault_rathole_tokens")
  if not isinstance(public_key, str) or not public_key:
    raise RatholeError(
      f"Missing vault_rathole_noise_public_key; run "
      f"task vault-secrets-ensure ENV={provider}"
    )
  if not isinstance(tokens, dict) or not isinstance(tokens.get(node), str):
    raise RatholeError(
      f"Missing vault_rathole_tokens.{node}; run "
      f"task vault-secrets-ensure ENV={provider}"
    )

  dest_dir = ROOT / ".state" / provider / "rathole"
  dest_dir.mkdir(parents=True, exist_ok=True)
  dest = dest_dir / f"{node}-install.sh"
  dest.write_text(
    render_client_install_script(
      node=node,
      hub_endpoint=hub_ip,
      listen_port=listen_port,
      token=tokens[node],
      noise_public_key=public_key,
    ),
    encoding="utf-8",
  )
  dest.chmod(0o700)
  uninstall = dest_dir / f"{node}-uninstall.sh"
  uninstall.write_text(
    render_client_uninstall_script(node=node),
    encoding="utf-8",
  )
  uninstall.chmod(0o700)
  print(dest)
  print(uninstall)
  return dest


def parse_arguments() -> argparse.Namespace:
  parser = argparse.ArgumentParser(description="Pin and render rathole bootstrap")
  parser.add_argument("action", choices=("fetch", "render-client"))
  parser.add_argument("--provider")
  parser.add_argument("--node")
  return parser.parse_args()


def main() -> int:
  arguments = parse_arguments()
  try:
    if arguments.action == "fetch":
      fetch_pinned_binary()
      return 0
    provider = arguments.provider or os.environ.get("ENV", "")
    if not provider:
      raise RatholeError("ENV or --provider is required")
    if not arguments.node:
      raise RatholeError("--node is required")
    render_client(provider, arguments.node)
  except (RatholeError, provider_vault.VaultError) as error:
    print(f"error: {error}", file=sys.stderr)
    return 1
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
