---
swarm_docker_base_url: https://download.docker.com/linux/ubuntu
swarm_docker_cache_dir: /var/cache/docker-swarm/docker
swarm_docker_runtime_dependencies:
  - bzip2
  - ca-certificates
  - iptables
  - libseccomp2
  - nftables
  - xz-utils
swarm_docker_architectures:
  x86_64: amd64
  aarch64: arm64
swarm_docker_artifacts:
  amd64:
    - package: containerd.io
      version: 2.3.3-1~ubuntu.26.04~resolute
      filename: containerd.io_2.3.3-1~ubuntu.26.04~resolute_amd64.deb
      path: dists/resolute/pool/stable/amd64/containerd.io_2.3.3-1~ubuntu.26.04~resolute_amd64.deb
      sha256: 6bf5d8ce94adb0876403753281a293b5af7ebeca51d6fac147d016fa40c0ebe5
    - package: docker-ce-cli
      version: 5:29.7.2-1~ubuntu.26.04~resolute
      filename: docker-ce-cli_29.7.2-1~ubuntu.26.04~resolute_amd64.deb
      path: dists/resolute/pool/stable/amd64/docker-ce-cli_29.7.2-1~ubuntu.26.04~resolute_amd64.deb
      sha256: 5967eae97b2c9c4b90ef28c271cbcaf2f0ca64d53ef2a69645423fda45b75885
    - package: docker-ce
      version: 5:29.7.2-1~ubuntu.26.04~resolute
      filename: docker-ce_29.7.2-1~ubuntu.26.04~resolute_amd64.deb
      path: dists/resolute/pool/stable/amd64/docker-ce_29.7.2-1~ubuntu.26.04~resolute_amd64.deb
      sha256: d12027201c0a10959a7146365423b8de0296686c82f3b5f8ebf29375a479b3e7
  arm64:
    - package: containerd.io
      version: 2.3.3-1~ubuntu.26.04~resolute
      filename: containerd.io_2.3.3-1~ubuntu.26.04~resolute_arm64.deb
      path: dists/resolute/pool/stable/arm64/containerd.io_2.3.3-1~ubuntu.26.04~resolute_arm64.deb
      sha256: 4751d71bf6170c54abd85504b2a9a98e4e9e2e4b3ce089009bbd0e5ce2a421a1
    - package: docker-ce-cli
      version: 5:29.7.2-1~ubuntu.26.04~resolute
      filename: docker-ce-cli_29.7.2-1~ubuntu.26.04~resolute_arm64.deb
      path: dists/resolute/pool/stable/arm64/docker-ce-cli_29.7.2-1~ubuntu.26.04~resolute_arm64.deb
      sha256: c02ca1849f71656a808b93e7e068f6c1025660a5265fae130d670f6b5ad5cc94
    - package: docker-ce
      version: 5:29.7.2-1~ubuntu.26.04~resolute
      filename: docker-ce_29.7.2-1~ubuntu.26.04~resolute_arm64.deb
      path: dists/resolute/pool/stable/arm64/docker-ce_29.7.2-1~ubuntu.26.04~resolute_arm64.deb
      sha256: 0d5a0e9d6356ff777f986f38613564d2beb7dfc77ba9b71366b8d82957b2d043
