---
all:
  children:
    controller:
      hosts:
        localhost:
          ansible_connection: local
    deployment:
      hosts:
        cust-local-1:
          ansible_host: 10.79.1.11
        cust-local-2:
          ansible_host: 10.79.1.12
        cust-local-3:
          ansible_host: 10.79.1.13
    wireguard_nodes:
      children:
        deployment: {}
